server:
  port: 8082
spring:
  application:
    name: mall-service
  cloud:
    nacos:
      discovery:
        server-addr: 30.16.95.140:8848
        namespace: 9977e1bd-4be2-4c34-9a04-c291be3ff606
      username: nacos
      password: nacos
  redis:
    host: 30.16.95.140
    #    host: 127.0.0.1
    port: 6379
    password: admin
    database: 1
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
