server:
  port: 8085
spring:
  application:
    name: trans-service
  cloud:
    nacos:
      discovery:
        server-addr: 30.16.95.140:8848
        group: 85ab69de-640b-4bb6-b62e-59d4bbcd7d93
      username: nacos
      password: nacos