server:
  port: 8083
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 30.16.95.140:8848
      username: nacos
      password: nacos
  redis:
    host: 30.16.95.140
    port: 6379
    password: admin
    database: 0
