server:
  port: 8081
spring:
  application:
    name: user-service
rocketmq:
  name-server: 30.16.96.140:9090
  producer:
    group: group1
logging:
  level:
    com.ebanma.cloud.user.dao: debug
