server:
  port: 8087
spring:
  application:
    name: seckill-service
  cloud:
    nacos:
      discovery:
        server-addr: 30.16.95.140:8848
        namespace: 7bdad1e8-52f0-4905-814a-d413d6d819e5
      username: nacos
      password: nacos