server:
  port: 8087
spring:
  application:
    name: seckill-service
  cloud:
    nacos:
      discovery:
        server-addr: 30.16.95.140:8848
        namespace: 9977e1bd-4be2-4c34-9a04-c291be3ff606
      username: nacos
      password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://30.16.95.143:3306/banma_project?useSSL=false&useUnicode=true&cahracterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.ebanma.cloud.seckill.dao: debug



