server:
  port: 10084
spring:
  application:
    name: post-service
#在application.yml中配置fastdfs的连接地址等信息
  cloud:
    nacos:
      discovery:
        server-addr: 30.16.95.140:8848
        namespace: 7bdad1e8-52f0-4905-814a-d413d6d819e5
      username: nacos
      password: nacos
  # 注意这个trackerList：如果是集群tracker的话以逗号分隔开就行 30.16.95.144
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  trackerList: 124.221.94.214:22122
  # 后续删除
  thumb-image:
    width: 150
    height: 150
  pool:
    max-total: 200
mybatis:
  mapper-locations: mapper/*.xml
